import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"
import { Platform } from "react-native";

type Product = {
  _id?: string;
  name: string;
  brand: string;
  description: string;
  category: string;
  average_rating: number | string;
  images: string[];
  prices: { size: 'S' | 'M' | 'L'; price: number | string }[];
  quantity: number;
}

type ProductsApiResponse = {
  products: Product[];
}

const PLATFORM_MAIN_URL = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';
const BASE_URL = `http://${PLATFORM_MAIN_URL}:4000/api/`;

// Define a service using a base URL and expected endpoints
export const productsApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: BASE_URL }),
  reducerPath: "productsApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Products", "Product"],
  endpoints: build => ({
    // Supply generics for the return type (in this case `ProductsApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getProducts: build.query<ProductsApiResponse, void>({
      query: () => 'products/',
      providesTags: result =>
        result
          ? [
            ...result.products.map(({ _id }) => ({
              type: 'Product' as const,
              id: _id,
            })),
            'Product',
          ]
          : ['Product'],
    }),
    getProductById: build.query<Product, string>({
      query: (id) => `/products/${id}`,
      providesTags: (result, error, id) => [{ type: 'Product', id }],
    }),
  }),
})

// Hooks are auto-generated by RTK-Query
// Same as `productsApiSlice.endpoints.getProducts.useQuery`
export const { useGetProductsQuery, useGetProductByIdQuery } = productsApiSlice